### ISSUE TITLE
error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sleakchat** [mitchmac/ServerlessWP#69]
Getting this error using a TiDB mysql db:

`/var/task/node_modules/serverlesswp/php-files/php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
Error: Timed out waiting for: tcp:127.0.0.1:8000
    at /var/task/node_modules/wait-on/lib/wait-on.js:131:31
    at doInnerSub (/var/task/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/var/task/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/var/task/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/var/task/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at AsyncAction.<anonymous> (/var/task/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
    at AsyncAction._execute (/var/task/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:79:18)
    at AsyncAction.execute (/var/task/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:67:26)
    at AsyncScheduler.flush (/var/task/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:38:33)
    at listOnTimeout (node:internal/timers:573:17)`
    
Anybody knows whats going wrong here? Thanks!

**Comment by erikksuzuki** [comment]
I have some troubleshooting experience with TiDB on Vercel:

After deploying to Vercel, change Node.js version is v18.0 in "General Settings"
In the project's function settings, change "Function Region" to match your database location
Change "Function Max Duration" from 10 seconds to 25 seconds
Replace line 46 in the wp-config.php file in your code repository with:
define( 'DB_COLLATE', 'utf8mb4_general_ci' );

In the "Deployments" tab find your most recent deployment and click the three-dot menu to redeploy the app.

**Comment by HallexCosta** [comment]
If you don´t wants to change the General Settings you can define the node version directly in package.json, with `{ engines": { "node": "18.x" } }`

Example:
```json
{
  "name": "serverlesswp-wordpress-starter",
  "version": "1.0.0",
  "description": "",
  "license": "MIT",
  "dependencies": {
    "serverlesswp": "^0.1.2"
  },
  "engines": { "node": "18.x" } 
}
```

**Comment by mitchmac** [comment]
Thanks for the reports and notes! This should now be fixed with Node 22 the default version used by serverlesswp with matching updated php binary files.
